### ISSUE TITLE
不能用

### ISSUE THREAD

**Issue by gaozhanbooo** [yhan219/utools-plugin#4]
按照文档说的弄完还是不能用

提示信息：
无相关服务的有效实例,应用没有绑定服务实例，可以新建服务实例，绑定服务实例。注：某些服务的翻译结果发音需要tts实例，需要在控制台创建语音合成实例绑定应用后方能使用。

**Comment by yhan219** [comment]
在应用详情里`绑定服务`，勾选`文本翻译`
